//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Torun.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Backup
    {
        public int id { get; set; }
        public int user_id { get; set; }
        public string filename { get; set; }
        public string filepath { get; set; }
    
        public virtual User User { get; set; }
    }
}
