//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Torun.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class plan_tracerDBEntities : DbContext
    {
        public plan_tracerDBEntities()
            : base("name=plan_tracerDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<plans> plans { get; set; }
        public virtual DbSet<todoList> todoList { get; set; }
        public virtual DbSet<users> users { get; set; }
        public virtual DbSet<WorkDone> WorkDone { get; set; }
    }
}
