//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Torun.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class plan_tracerDBEntities : DbContext
    {
        public plan_tracerDBEntities()
            : base("name=plan_tracerDBEntities")
        {
            this.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Log> Logs { get; set; }
        public virtual DbSet<Plan> Plans { get; set; }
        public virtual DbSet<TodoList> TodoLists { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<WorkDone> WorkDones { get; set; }
        public virtual DbSet<Backup> Backups { get; set; }
        public virtual DbSet<Setting> Settings { get; set; }
    }
}
