//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Torun.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class plans
    {
        public int id { get; set; }
        public Nullable<int> work_id { get; set; }
        public Nullable<System.DateTime> add_time { get; set; }
        public Nullable<System.DateTime> work_plan_time { get; set; }
    
        public virtual todoList todoList { get; set; }
    }
}
