//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Torun.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class users
    {
        public int id { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
        public string username { get; set; }
        public string pc_name { get; set; }
        public string pc_username { get; set; }
        public Nullable<System.DateTime> last_login { get; set; }
        public Nullable<byte> login_status { get; set; }
        public Nullable<byte> user_status { get; set; }
    }
}
