//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Torun.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkDone
    {
        public int id { get; set; }
        public Nullable<int> work_id { get; set; }
        public Nullable<System.DateTime> workDoneTime { get; set; }
        public string description { get; set; }
        public Nullable<System.DateTime> add_time { get; set; }
        public Nullable<byte> status { get; set; }
    }
}
